const contenido = {
  meta: {
    nombre: 'VIERNES OS',
    version: '1.37',
    titular: { es: 'Bruno Fragoso — Desarrollo web, datos y automatización con IA',
               en: 'Bruno Fragoso — Web development, data and AI automation' },
  },

  boot: {
    post: [
      'VIERNES BIOS v1.37 — (c) 1987',
      'CPU ....... OK',
      'MEM ....... 640K OK',
      'VIDEO ..... CGA/EGA DETECTADO',
      'DISCO ..... /dev/bruno MONTADO',
    ],
    saludo: 'hello, world',
    pregunta: { es: '¿INICIAR SESIÓN? [S/N]', en: 'LOG IN? [Y/N]' },
    saltar: { es: 'saltar intro', en: 'skip intro' },
    rechazo: { es: 'CONEXIÓN TERMINADA', en: 'CONNECTION TERMINATED' },
    reproche: { es: '...¿en serio?', en: '...really?' },
    reintentar: { es: '[REINTENTAR]', en: '[RETRY]' },
    entrando: { es: 'ACCESO CONCEDIDO', en: 'ACCESS GRANTED' },
  },

  secciones: [
    { id: 'whoami',      etiqueta: { es: 'WHOAMI',      en: 'WHOAMI' } },
    { id: 'archivos',    etiqueta: { es: 'ARCHIVOS',    en: 'FILES' } },
    { id: 'procesos',    etiqueta: { es: 'PROCESOS',    en: 'PROCESSES' } },
    { id: 'stack',       etiqueta: { es: 'STACK',       en: 'STACK' } },
    { id: 'trayectoria', etiqueta: { es: 'TRAYECTORIA', en: 'HISTORY' } },
    { id: 'contacto',    etiqueta: { es: 'CONTACTO',    en: 'CONTACT' } },
  ],

  whoami: {
    nombre: 'Bruno Fragoso Márquez',
    ubicacion: { es: 'Ciudad de México', en: 'Mexico City' },
    parrafos: [
      { es: 'Desarrollador full-stack y estudiante de Inteligencia de Datos y Ciberseguridad en la Universidad Panamericana. Actualmente trabajo en un hedge fund, construyendo herramientas de análisis para investigación de materias primas.',
        en: 'Full-stack developer and student of Data Intelligence and Cybersecurity at Universidad Panamericana. I currently work at a hedge fund, building analysis tooling for commodities research.' },
      { es: 'Cofundé una agencia digital y trabajo por mi cuenta entregando aplicaciones web y automatizaciones. Me interesa el punto donde el software deja de ser una demo y empieza a sostener decisiones reales.',
        en: 'I co-founded a digital agency and work independently delivering web applications and automations. I care about the point where software stops being a demo and starts supporting real decisions.' },
    ],
    pilares: [
      { es: 'Desarrollo web', en: 'Web development' },
      { es: 'Datos y análisis', en: 'Data and analysis' },
      { es: 'Automatización e IA aplicada', en: 'Automation and applied AI' },
    ],
  },

  archivos: [
    {
      id: 'commodities',
      nombre: { es: 'ANALISIS-COMMODITIES', en: 'COMMODITIES-ANALYSIS' },
      etiqueta: 'FIN',
      anio: '2025',
      resumen: { es: 'Plataforma de análisis técnico de materias primas para un hedge fund.',
                 en: 'Technical analysis platform for commodities research at a hedge fund.' },
      detalle: { es: 'Visualización de contratos de futuros por producto y vencimiento, motor de series derivadas para construir spreads y butterflies con pesos configurables, análisis de estacionalidad año a año, e indicadores SMA-20 y MACD. Incluye carga de archivos Parquet desde la interfaz para actualizar la base de precios.',
                 en: 'Futures contract visualization by product and expiry, a derived-series engine to build spreads and butterflies with configurable weights, year-over-year seasonality analysis, and SMA-20 and MACD indicators. Includes Parquet upload from the interface to refresh the price database.' },
      stack: ['FastAPI', 'React', 'Pandas', 'SQLAlchemy', 'Docker'],
      enlace: null,
    },
    {
      id: 'automatizacion-ia',
      nombre: { es: 'AUTOMATIZACION-IA', en: 'AI-AUTOMATION' },
      etiqueta: 'IA',
      anio: '2025',
      resumen: { es: 'Flujos de automatización con pasos de IA, entregados a clientes.',
                 en: 'Automation workflows with AI steps, delivered to clients.' },
      detalle: { es: 'Diseño e implementación de flujos en n8n que integran modelos de lenguaje dentro de procesos de negocio, entregados a clientes de la agencia y de trabajo freelance. Corren en producción.',
                 en: 'Design and implementation of n8n workflows that embed language models inside business processes, delivered to agency and freelance clients. Running in production.' },
      stack: ['n8n', 'APIs de IA', 'Webhooks', 'REST'],
      enlace: null,
    },
    {
      id: 'plantasia',
      nombre: 'PLANTASIA',
      etiqueta: 'IoT',
      anio: '2025',
      resumen: { es: 'Plataforma IoT de cuidado de plantas, de hardware a navegador.',
                 en: 'IoT plant-care platform, from hardware to browser.' },
      detalle: { es: 'Macetas inteligentes con ESP32 que miden temperatura, luz y humedad y reportan a una API, más una aplicación web para monitorearlas en tiempo real y gestionar cada planta. Todo el ecosistema levanta con Docker Compose: base de datos, backend y frontend.',
                 en: 'Smart planters built on ESP32 that measure temperature, light and humidity and report to an API, plus a web app to monitor them in real time and manage each plant. The whole stack comes up with Docker Compose: database, backend and frontend.' },
      stack: ['React', 'Vite', 'Flask', 'PostgreSQL', 'C++', 'Docker'],
      enlace: 'https://github.com/Viernes137/Plantasia',
    },
    {
      id: 'omniscient',
      nombre: 'OMNISCIENT',
      etiqueta: { es: 'DATOS', en: 'DATA' },
      anio: '2025',
      resumen: { es: 'Mapeo de riesgo urbano con reportes de la comunidad.',
                 en: 'Urban risk mapping with community reporting.' },
      detalle: { es: 'Aplicación full-stack con mapa interactivo y reportes comunitarios en tiempo real, sobre un pipeline de datos propio: recolección, limpieza, modelado y visualización. La predicción de robos usa regresión lineal sobre incidentes históricos y patrones de ubicación.',
                 en: 'Full-stack application with an interactive map and real-time community reporting, built on a hand-rolled data pipeline: collection, cleaning, modeling and visualization. Theft prediction uses linear regression over historical incidents and location patterns.' },
      stack: ['Python', 'Pandas', 'scikit-learn', 'JavaScript'],
      enlace: null,
    },
    {
      id: 'psyche',
      nombre: 'PSYCHE',
      etiqueta: { es: 'WEB', en: 'WEB' },
      anio: '2022-2023',
      resumen: { es: 'Plataforma de telepsicología multiusuario.',
                 en: 'Multi-user telepsychology platform.' },
      detalle: { es: 'Plataforma donde psicólogos y pacientes se conectan, agendan sesiones y comparten recursos. Construí la lógica de backend, el esquema de base de datos y la interfaz, con foco en el manejo seguro de datos sensibles.',
                 en: 'A platform where psychologists and patients connect, schedule sessions and share resources. I built the backend logic, the database schema and the interface, focused on handling sensitive data safely.' },
      stack: ['JavaScript', 'HTML/CSS', 'SQL'],
      enlace: null,
    },
    {
      id: 'academicos',
      nombre: { es: 'TRABAJO-ACADEMICO', en: 'ACADEMIC-WORK' },
      etiqueta: 'UP',
      anio: '2024-2025',
      resumen: { es: 'Proyectos de carrera: sistemas operativos, arquitectura de datos, bases de datos.',
                 en: 'Coursework: operating systems, data architecture, databases.' },
      detalle: { es: 'Simulación de planificación de sistemas operativos en Python, proyecto de arquitectura de datos en Assembly, y un dashboard sobre una base de datos relacional avanzada en JavaScript.',
                 en: 'An operating-system scheduling simulation in Python, a data architecture project in Assembly, and a dashboard over an advanced relational database in JavaScript.' },
      stack: ['Python', 'Assembly', 'JavaScript', 'SQL'],
      enlace: 'https://github.com/Viernes137',
    },
  ],

  procesos: [
    {
      id: 'ia-profunda',
      nombre: { es: 'profundizacion-ia', en: 'ai-deep-dive' },
      estado: { es: 'EN CURSO', en: 'RUNNING' },
      detalle: { es: 'Más allá de los modelos lineales: arquitecturas modernas, evaluación honesta y puesta en producción.',
                 en: 'Beyond linear models: modern architectures, honest evaluation, and getting things into production.' },
    },
    {
      id: 'viernes-os',
      nombre: 'viernes-os',
      estado: { es: 'EN CURSO', en: 'RUNNING' },
      detalle: { es: 'Este sitio. Sin frameworks, sin build, sin dependencias.',
                 en: 'This site. No frameworks, no build step, no dependencies.' },
    },
  ],

  stack: [
    { grupo: { es: 'Lenguajes', en: 'Languages' },
      items: ['Python', 'JavaScript', 'SQL', 'C#', 'C++', 'HTML/CSS'] },
    { grupo: { es: 'Datos', en: 'Data' },
      items: ['Pandas', 'NumPy', 'scikit-learn', 'Power BI', 'PostgreSQL'] },
    { grupo: { es: 'Web', en: 'Web' },
      items: ['React', 'Vite', 'FastAPI', 'Flask', 'REST'] },
    { grupo: { es: 'Herramientas', en: 'Tools' },
      items: ['Git', 'Docker', 'n8n', 'Linux', 'Agile/Scrum'] },
  ],

  trayectoria: [
    { periodo: { es: '2025 — hoy', en: '2025 — present' },
      titulo: { es: 'Desarrollador · hedge fund', en: 'Developer · hedge fund' },
      detalle: { es: 'Herramientas de análisis técnico para investigación de materias primas.',
                 en: 'Technical analysis tooling for commodities research.' } },
    { periodo: { es: 'feb 2025 — hoy', en: 'Feb 2025 — present' },
      titulo: { es: 'Cofundador y desarrollador full-stack · Mablo Digital Agency',
                en: 'Co-founder and full-stack developer · Mablo Digital Agency' },
      detalle: { es: 'Agencia fundada con tres socios. Sitios, aplicaciones web y automatizaciones para clientes; dos clientes entregados en el primer mes.',
                 en: 'Agency founded with three partners. Websites, web applications and automations for clients; two clients delivered in the first month.' } },
    { periodo: { es: 'A demanda', en: 'On demand' },
      titulo: { es: 'Desarrollador web freelance', en: 'Freelance web developer' },
      detalle: { es: 'Proyectos de punta a punta: relevamiento, arquitectura, desarrollo y despliegue.',
                 en: 'End-to-end projects: scoping, architecture, development and deployment.' } },
    { periodo: { es: '2024 — hoy', en: '2024 — present' },
      titulo: { es: 'Universidad Panamericana', en: 'Universidad Panamericana' },
      detalle: { es: 'Inteligencia de Datos y Ciberseguridad. Prácticas en admisiones para la división de Ingeniería y Tecnología, y coordinación de voluntariado en el Programa de Compromiso Social.',
                 en: 'Data Intelligence and Cybersecurity. Admissions internship for the Engineering and Technology division, and volunteer coordination in the Social Commitment Program.' } },
    { periodo: { es: '2019 — 2023', en: '2019 — 2023' },
      titulo: { es: 'CECyT 9 "Juan de Dios Bátiz" · IPN', en: 'CECyT 9 "Juan de Dios Bátiz" · IPN' },
      detalle: { es: 'Bachillerato técnico con especialidad en Programación.',
                 en: 'Technical high school diploma specialized in Programming.' } },
  ],

  contacto: {
    lineas: [
      { es: 'La forma de contactarme es LinkedIn.', en: 'The way to reach me is LinkedIn.' },
    ],
    enlaces: [
      { etiqueta: 'LinkedIn', url: 'https://www.linkedin.com/in/brunofrag' },
      { etiqueta: 'GitHub', url: 'https://github.com/Viernes137' },
    ],
    idiomas: [
      { es: 'Español (nativo)', en: 'Spanish (native)' },
      { es: 'Inglés (fluido)', en: 'English (fluent)' },
      { es: 'Francés (básico)', en: 'French (basic)' },
    ],
  },
};

export default contenido;
